name: Run Parasoft Jtest
  # You may pin to the exact commit or the version.
  # uses: parasoft/run-jtest-action@ae433ddf714970d4a40842e7a4788facd508d68d
  uses: parasoft/run-jtest-action@2.0.0
  with:
    # Installation folder of Parasoft Jtest. If not specified, the cpptestcli executable must be added to PATH.
    installDir: # optional
    # Working directory for running Jtest.
    workingDir: # optional, default is ${{ github.workspace }}
    # Test configuration to be used for code analysis.
    testConfig: # optional, default is builtin://Recommended Rules
    # Output folder for reports from code analysis.
    reportDir: # optional, default is reports
    # Format of reports from code analysis.
    reportFormat: # optional, default is xml,html,sarif
    # Input scope for analysis.
    input: # optional, default is jtest.data.json
    # Additional parameters for the jtestcli executable.
    additionalParams: # optional, 
